#!/bin/bash

EXTERNAL="external"
GLADDIR="$EXTERNAL/glad"
GLADINC="$GLADDIR/include"
GLADSRC="$GLADDIR/src"

CC="gcc"
CFLAGS="-Wall -Wpedantic -ggdb -std=c11"
CDEFINES=""
CINCLUDES="-I$EXTERNAL -I$GLADINC"
CFILES="$GLADSRC/gl.c main.c"
CLIBS="-lSDL2 -lGL"

EXEC="main"

echo "$CC $CFLAGS $CDEFINES $CINCLUDES $CFILES -o $EXEC $CLIBS"
$CC $CFLAGS $CDEFINES $CINCLUDES $CFILES -o $EXEC $CLIBS

echo "./$EXEC"
./$EXEC
